# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and Build 🔧
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        mkdocs build
    - name: Deploy 🚀
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
    - name: Sync to Gitee 🔄
      uses: wei/git-sync@v3
      if: github.event_name == 'push'
      with:
        source_repo: "cuit-icec/cuit-icec.github.io"
        source_branch: "refs/remotes/source/*"
        destination_repo: "git@gitee.com:cuit_icec/icec_wiki.git"
        destination_branch: "refs/heads/*"
        ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
    - name: Gitee Pages Action
      uses: yanglbme/gitee-pages-action@v1.2.6
      if: github.event_name == 'push'
      with:
        # The Gitee username, like yanglbme
        gitee-username: tfx2001
        # The Gitee password
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # The Gitee repository, like doocs/leetcode
        gitee-repo: cuit_icec/icec_wiki/
        # Which branch to build
        branch: gh-pages
        # Which directory to build
        directory: ''
        # Use force https or not
        https: true
